const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const AUTH_COOKIE_NAME = process.env.NEXT_PUBLIC_AUTH_COOKIE_NAME as string;
const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL!;
const GRAPHQL_URL = process.env.NEXT_PUBLIC_GRAPHQL_URL!;
export { API_BASE_URL, AUTH_COOKIE_NAME, BACKEND_URL, GRAPHQL_URL};
